"""Initial migration

Revision ID: 331ec36b0f47
Revises: 
Create Date: 2025-07-22 09:42:51.818280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331ec36b0f47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entidade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pos_x', sa.Float(), nullable=True),
    sa.Column('pos_y', sa.Float(), nullable=True),
    sa.Column('pos_z', sa.Float(), nullable=True),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('path_modelo', sa.String(length=300), nullable=True),
    sa.Column('hp', sa.SmallInteger(), nullable=True),
    sa.Column('qnt_deslocamento', sa.SmallInteger(), nullable=True),
    sa.Column('qnt_campo_visao', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mapa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('campanha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('id_mestre', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_mestre'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inimigo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dano', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['entidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jogador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['entidade.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objeto_de_interacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_mapa', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('path_modelo', sa.String(length=300), nullable=True),
    sa.Column('pos_x', sa.Float(), nullable=True),
    sa.Column('pos_y', sa.Float(), nullable=True),
    sa.Column('pos_z', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_mapa'], ['mapa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mapa_em_campanha',
    sa.Column('id_campanha', sa.Integer(), nullable=False),
    sa.Column('id_mapa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_campanha'], ['campanha.id'], ),
    sa.ForeignKeyConstraint(['id_mapa'], ['mapa.id'], ),
    sa.PrimaryKeyConstraint('id_campanha', 'id_mapa')
    )
    op.create_table('usuario_em_campanha',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_campanha', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_campanha'], ['campanha.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_campanha')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_em_campanha')
    op.drop_table('mapa_em_campanha')
    op.drop_table('objeto_de_interacao')
    op.drop_table('jogador')
    op.drop_table('inimigo')
    op.drop_table('campanha')
    op.drop_table('usuario')
    op.drop_table('mapa')
    op.drop_table('entidade')
    # ### end Alembic commands ###
